---
- name: "Suse Derivatives: Download host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ inventory_hostname }}&os_type=linux_rpm&agent_type=host_name"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.host }}"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  when: |
    checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme"
  become: false
  register: checkmk_agent_download_state
  # This task may fail, as we fall back to the generic agent in that case
  failed_when: 'false'
  changed_when: 'false'
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "Suse Derivates: Transfer host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.builtin.copy:
    src: "{{ checkmk_agent_agent.file.host }}"
    dest: "{{ checkmk_agent_agent.file.host }}"
    mode: 0644
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_download_state.status == 200
    and checkmk_agent_delegate_download != inventory_hostname
  tags:
    - download-package

- name: "Suse Derivatives: Install host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  become: true
  community.general.packaging.os.zypper:
    name: "{{ checkmk_agent_agent.file.host }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_download_state.status == 200
  tags:
    - install-package

- name: "Suse Derivatives: Download GENERIC Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=linux_rpm&agent_type=generic"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  become: false
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_download_state.status != 200
  retries: 3
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "Suse Derivates: Transfer GENERIC Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.builtin.copy:
    src: "{{ checkmk_agent_agent.file.cee }}"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    mode: 0644
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_download_state.status != 200
    and checkmk_agent_delegate_download != inventory_hostname
  tags:
    - download-package

- name: "Suse Derivatives: Install GENERIC Checkmk {{ checkmk_agent_edition | upper }} Agent."
  become: true
  community.general.packaging.os.zypper:
    name: "{{ checkmk_agent_agent.file.cee }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_download_state.status != 200
  tags:
    - install-package

- name: "Suse Derivatives: Install Checkmk CRE Agent."
  become: true
  community.general.packaging.os.zypper:
    name: "{{ checkmk_agent_agent.file.cre }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: checkmk_agent_edition == "cre"
  tags:
    - install-package
