version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=${cloudflare_api_key}
      - ZONE=${cloudflare_zone}
      - PROXIED=true
      - PUID=1000
      - PGID=1000
