---
- name: Install Python
  hosts: all
  remote_user: root
  gather_facts: false

  tasks:
    - name: Check for Python
      remote_user: root
      ansible.builtin.raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      remote_user: root
      ansible.builtin.raw: test -e /usr/bin/apt && (apt -y update && apt install -y python3 python3-pip) || (yum -y install python3 python3-pip)
      when: check_python.rc != 0
