- name: Update packages via apt or yum depending on distro
  hosts: all

  tasks:
    - name: Update apt packages
      become: true
      apt:
        name: '*'
        state: latest
        update_cache: yes
        cache_valid_time: 86400 #One day
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Update yum packages
      become: true
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when:
        - ansible_distribution == "Amazon"