
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # hp-laptop
  # config.vm.box = "ubuntu/focal64"

  # M1 mac
  config.vm.box = "jeffnoxon/ubuntu-20.04-arm64"
  # config.vm.box_download_insecure = true

  # config.vm.network "forwarded_port", guest: 9090, host: 725

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update -y
  #   sudo apt-get install ca-certificates curl gnupg lsb-release -y

  #   sudo mkdir -p /etc/apt/keyrings
  #   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  #   echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  #   sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
  #   sudo usermod -aG docker $USER
  #   newgrp docker
  # SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/servers/test.yaml"
    ansible.config_file = "../ansible/servers/ansible.cfg"
  end
end

