---
version: '3'
services:
  lldap:
    image: nitnelave/lldap:stable
    container_name: lldap
    # Change this to the user:group you want.
    user: "1000:1000"
    ports:
      # For LDAP
      - "3890:3890"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "./lldap_data:/data"
    environment:
      - LLDAP_JWT_SECRET=${lldap_jwt_secret}
      - LLDAP_LDAP_USER_PASS=${zpassword}
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
