version: '3.3'
services:
    mysqld-exporter:
        network_mode: host
        # ports:
        #     - '9104:9104'
        environment:
            - 'DATA_SOURCE_NAME={mysql_db_user}:${mysql_db_password}@(${mysql_db_host}:3306)/'
        image: prom/mysqld-exporter
        container_name: mysqld_exporter
        restart: unless-stopped