# this was an old and simple way of installing docker - I now use the the docker-ce role but keep this for historical purposes
- name: Install docker
  hosts: all

  tasks:
    - name: Install apt-transport-https
      become: true
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      become: true
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: add user to docker group
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        group: docker
        state: present