# tasks file for prometheus
---
- name: Prometheus | create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "/home/{{prom_user}}/prometheus"

- name: Prometheus | prometheus configuration file
  template:
    dest: "/home/{{prom_user}}/prometheus/prometheus.yml"
    force: true
    src: prometheus-prometheus-yml.j2
    mode: 0700
  register: prometheus_configuration

- name: Docker | docker-compose file
  template:
    dest: "/home/{{prom_user}}/prometheus/docker-compose.yml"
    force: true
    src: docker-docker-compose-yml.j2
    mode: 0700
  register: docker_compose_configuration

- name: Create docker network and volume
  shell: "{{ item.cmd }}"
  with_items:
    - cmd: 'docker network create {{ prometheus_docker_network }}'
    - cmd: 'docker volume create {{ prometheus_docker_data_volume }}'

# for older installs of docker-compose
- name: Check is docker-compose installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install
  ignore_errors: true

- debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 0 if installed or 127 if not
- debug: var=is_docker_compose_install

- name: Create docker containers with docker-compose
  shell: docker-compose up -d --force-recreate
  ignore_errors: true
  when: is_docker_compose_install.rc == 0
  args:
    chdir: '/home/{{prom_user}}/prometheus/'

- name: Create docker containers with docker compose
  shell: docker compose up -d --force-recreate
  ignore_errors: true
  when: is_docker_compose_install.rc != 0
  args:
    chdir: '/home/{{prom_user}}/prometheus/'






